/**
 * A refusal the workspace's `commands:` could have granted (gh #285).
 *
 * Measured by a peer session on a live unattended run (tldrx 0.18.2→0.18.3):
 * four developers died and two reviews ran over ~3 h on ONE story whose
 * acceptance criterion required the migration to be generated by `dotnet ef`,
 * in a workspace declaring `commands: {build, test, test_fast, lint}`. The
 * fourth developer wrote, verbatim, "dotnet ef is not grantable, confirmed
 * absent from .tldrx/workspace.yml:1 commands and refused twice already... No
 * code changes made this round." The information existed at every step and
 * nothing read it.
 *
 * Two halves were tried. This file holds the one that shipped: at the moment of
 * the refusal the declared commands ARE known, so the recorded reason can name
 * the operator's cure exactly — no guessing and no prose. The other half, a
 * Plan-time reader of acceptance PROSE, was measured out of this branch and
 * filed instead: see the issue named in the CHANGELOG. A story's ```dod block
 * is structured and already REFUSES a command no slot declares; the cases below
 * are guards on that, not proofs of new work.
 */
import { describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { validatePlan } from "../src/core/plan/validatePlan.ts";
import { classifyRefusal, refusalCure } from "../src/core/build/refusalKind.ts";
import { grantsCommand, slotForCommand } from "../src/core/build/developerGrants.ts";

const DECLARED = new Set(["dotnet build", "dotnet test", "dotnet format"]);

function story(acceptance: readonly string[], dod: string): string {
  return `---
version: 1
id: S5
epic: E1
title: "EF migration for the tenancy columns"
repo: lab
status: todo
depends_on: []
touches: ["src/Data/"]
acceptance: ${JSON.stringify(acceptance)}
test_plan: ["Unit: the context builds"]
evidence: []
---

# S5

\`\`\`dod
${dod}
\`\`\`
`;
}

const EPIC = `---
version: 1
id: E1
title: "Tenancy"
repos: [lab]
stories: [S5]
branch: epic/tenancy
status: todo
---

# E1
`;

function planDir(acceptance: readonly string[], dod: string): string {
  const dir = mkdtempSync(join(tmpdir(), "tldrx-undeclared-"));
  const files: Record<string, string> = {
    "stories/S5.md": story(acceptance, dod),
    "epics/E1.md": EPIC,
    "waves.yml": "version: 1\nwaves:\n  - {id: W1, stories: [S5]}\n",
  };
  for (const [rel, content] of Object.entries(files)) {
    const path = join(dir, rel);
    mkdirSync(join(path, ".."), { recursive: true });
    writeFileSync(path, content, "utf8");
  }
  return dir;
}

describe("a DoD command no `commands:` slot declares (gh #285) — REFUSES", () => {
  test("the plan fails, naming the command", () => {
    const report = validatePlan(planDir(["The migration exists"], "dotnet ef migrations add Tenancy"), DECLARED);
    expect(report.ok).toBe(false);
    expect(report.issues.map((i) => i.message).join(" | "))
      .toContain("not one of .tldrx/workspace.yml's commands");
  });

  test("a declared command plus arguments is NOT a declared command — the rule is byte equality", () => {
    const report = validatePlan(planDir(["The migration exists"], "dotnet test --filter Tenancy"), DECLARED);
    expect(report.ok).toBe(false);
  });
});

describe("an `unknown` refusal names the operator's cure (gh #285)", () => {
  test("with the declared commands in hand, the cure names the slot to add", () => {
    const cure = refusalCure(classifyRefusal("dotnet ef migrations add Tenancy", DECLARED));
    expect(cure).toContain("commands:");
    expect(cure).toContain("dotnet ef");
  });

  test("without them the classification is unchanged — one arg, `unknown`, no cure", () => {
    expect(classifyRefusal("dotnet ef migrations add Tenancy")).toEqual({ kind: "unknown" });
    expect(refusalCure(classifyRefusal("dotnet ef migrations add Tenancy"))).toBe("");
  });

  test("a line a declared command already grants is not blamed on `commands:`", () => {
    expect(classifyRefusal("dotnet test --filter X", DECLARED)).toEqual({ kind: "unknown" });
  });

  test("an ungranted git verb keeps #278's verb cure, not this one", () => {
    // `git status` used to stand here; it is granted since #287, so the verb that
    // carries the case is one that is still outside the allowance.
    expect(classifyRefusal("git stash", DECLARED)).toEqual({ kind: "verb", verb: "stash", equivalent: null });
  });

  test("a `git -C` line is #287's `elsewhere`, never blamed on `commands:` either", () => {
    expect(classifyRefusal("git -C /elsewhere log", DECLARED)).toEqual({ kind: "elsewhere", option: "-C" });
  });
});

describe("the `commands:` slot a refused line asks for (gh #285)", () => {
  const cases: readonly [string, string][] = [
    ["dotnet ef migrations add Tenancy", "dotnet ef"],
    ["npm run e2e", "npm run"],
    ["prisma migrate deploy", "prisma migrate"],
    // An ARGUMENT never rides into the slot: a slot carrying one story's file
    // name would grant that one invocation and nothing else.
    ["sha256sum s1.txt", "sha256sum"],
    ["pytest -q", "pytest"],
    ["alembic upgrade head", "alembic upgrade"],
  ];
  for (const [line, slot] of cases) {
    test(`\`${line}\` asks for the slot \`${slot}\``, () => {
      expect(slotForCommand(line)).toBe(slot);
      const kind = classifyRefusal(line, DECLARED);
      expect(kind).toEqual({ kind: "undeclared", slot });
    });
  }

  test("the slot it names is one that would actually grant the line", () => {
    for (const [line] of cases) {
      expect(grantsCommand([slotForCommand(line)], line)).toBe(true);
    }
  });
});
