/**
 * The two MEASURED fields an evidence-note skeleton starts with: how many
 * citations this stage's outputs carry, and how many touched paths the plan
 * declares.
 *
 * Both lived inside `src/cli/commands/gate.ts` and had exactly one reader — the
 * `gate template` command a person runs. The engine's own gate signer (gh #198)
 * hands its sub-agent the SAME skeleton, generated by the SAME function, so a
 * note written by a person and a note written by the engine cannot start from two
 * different forms. That is the whole reason these are a leaf: one implementation
 * per derivation (AGENTS.md §7), and the second reader is what forced it out of
 * the command file.
 *
 * Data in, numbers out — no `RunStore`, no session, no `ctx` object beyond the
 * `PathContext` the resolver itself is defined over.
 */
import { existsSync, readFileSync } from "node:fs";
import { resolveMany, type PathContext } from "../facilitator/paths.ts";
import { listItems, parseSrcToken } from "../text/handoff.ts";
import { parseFrontMatter } from "../schemas/frontMatter.ts";
import { parseYaml } from "../yaml.ts";

/**
 * How many `src` citations this stage's declared outputs carry — the `of` half of
 * `citations: {sampled, of, …}`.
 *
 * Counted with the §2.8 tokenizer over the §2.8 notion of a list item, across
 * every declared output that is a Markdown file on disk. Patterns
 * (`03-plan/stories/<id>.md`) go through `resolveMany`, so a Plan stage's `of` is
 * the citations across the stories it actually wrote rather than zero.
 */
export function countCitations(outputs: readonly string[], ctx: PathContext): number {
  let total = 0;
  for (const declared of outputs) {
    if (!declared.endsWith(".md")) continue;
    for (const hit of resolveMany(declared, ctx)) {
      const text = readOrNull(hit.absolute);
      if (text === null) continue;
      for (const item of listItems(text)) {
        total += parseSrcToken(item)?.refs.length ?? 0;
      }
    }
  }
  return total;
}

/**
 * The touched paths the plan declares, deduplicated — the set an agent gate has
 * to audit, and what `touches.audited` starts at.
 *
 * This is the DECLARED surface only. Measuring what the branch actually changed
 * against it is the `boundary` condition (design §A.4, wave 2B); this counts what
 * there is to look at, and its callers say so rather than pretending the audit
 * has happened.
 */
export function countDeclaredTouches(ctx: PathContext): number {
  const paths = new Set<string>();
  for (const hit of resolveMany("03-plan/stories/<id>.md", ctx)) {
    const text = readOrNull(hit.absolute);
    if (text === null) continue;
    const doc = parseFrontMatter(text).doc;
    for (const entry of listOf(doc, "touches")) paths.add(entry);
  }
  if (paths.size === 0) {
    const text = readOrNull(resolveMany("04-build/implicit-plan.yml", ctx)[0]?.absolute ?? "");
    if (text !== null) {
      for (const entry of listOf(safeYaml(text), "touches")) paths.add(entry);
    }
  }
  return paths.size;
}

function listOf(doc: unknown, key: string): readonly string[] {
  if (typeof doc !== "object" || doc === null) return [];
  const value = (doc as Record<string, unknown>)[key];
  return Array.isArray(value) ? value.filter((entry): entry is string => typeof entry === "string") : [];
}

function safeYaml(text: string): unknown {
  try {
    return parseYaml(text);
  } catch {
    return null;
  }
}

function readOrNull(path: string): string | null {
  if (path === "" || !existsSync(path)) return null;
  try {
    return readFileSync(path, "utf8");
  } catch {
    return null;
  }
}
