/**
 * The tolerant common core of "read `.tldrx/workspace.yml`, then walk its `repos[]`" —
 * shared by every leaf that derives something per-repo from that file:
 * `stackExperts.ts` (`<language>-stack` expert names for a run's repos) and
 * `stackPacks.ts` (the stack-packs overlays/skills state). Before this file existed the
 * two duplicated the same existsSync → try/catch parse → repos-array walk near-verbatim
 * (found in review); AGENTS.md §7 — one implementation per derivation.
 *
 * Tolerant by design, same as both callers were before: a missing file, a file that
 * fails to parse, a `repos` that isn't an array, or a row that isn't a mapping with a
 * string `name` all resolve to "nothing here" rather than throwing — `workspace.yml` is
 * regenerated by `tldrx init` and a reader must survive every shape an older or
 * hand-edited version of it can take.
 */
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { PROJECT_FRAMEWORK_DIR } from "../paths.ts";
import { parseYaml } from "../yaml.ts";

/** One `repos[]` row that at least named itself — everything else on it is unvalidated. */
export interface WorkspaceRepoRow {
  readonly name: string;
  readonly [key: string]: unknown;
}

/** `.tldrx/workspace.yml` under `root`, parsed. `null` when absent, unreadable, or not YAML. */
export function readWorkspaceDocument(root: string): unknown {
  const path = join(root, PROJECT_FRAMEWORK_DIR, "workspace.yml");
  if (!existsSync(path)) return null;
  try {
    return parseYaml(readFileSync(path, "utf8"));
  } catch {
    return null;
  }
}

/**
 * `doc.repos`, filtered to the rows a caller can actually use: a mapping with a string
 * `name`. Anything else — `doc` not a mapping, no `repos` array, a row that is `null`,
 * a primitive, or nameless — is silently dropped rather than thrown on.
 */
export function workspaceRepoRows(doc: unknown): readonly WorkspaceRepoRow[] {
  if (typeof doc !== "object" || doc === null) return [];
  const list = (doc as Record<string, unknown>).repos;
  if (!Array.isArray(list)) return [];

  const rows: WorkspaceRepoRow[] = [];
  for (const row of list as unknown[]) {
    if (typeof row !== "object" || row === null) continue;
    const record = row as Record<string, unknown>;
    if (typeof record.name !== "string") continue;
    rows.push(record as WorkspaceRepoRow);
  }
  return rows;
}

/** Elements of `value` that are strings — the coercion every `repos[].<list-field>` needs. */
export function strings(value: unknown): readonly string[] {
  return Array.isArray(value) ? (value as unknown[]).filter((item): item is string => typeof item === "string") : [];
}
